port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: Singapore 1
    server: sing1.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: shopvpn4g.vn
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: Singapore 2 - [TLS]
    server: sing2.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: data1shopvpn4g
    udp: true
  - name: Singapore 3
    server: sing3.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: shopvpn4g.vn
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: Singapore 4 - [TLS]
    server: sing4.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: data1shopvpn4g
    udp: true
  - name: ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 1âš¡ğŸ‘‘
    server: hnvip1.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt3shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 2âš¡ğŸ‘‘
    server: hnvip2.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: dt3shopvpn4g
    udp: true
  - name: ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 3âš¡ğŸ‘‘
    server: hnvip3.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt3shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 4âš¡ğŸ‘‘
    server: hnvip4.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: dt3shopvpn4g
    udp: true
  - name: ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 5âš¡ğŸ‘‘
    server: hnvip5.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt3shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 7âš¡ğŸ‘‘
    server: hcmvip1.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt3shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 8âš¡ğŸ‘‘
    server: hcmvip2.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: dt3shopvpn4g
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 1âš¡
    server: data2hn1.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt2shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 2âš¡
    server: data2hn2.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: dt2shopvpn4g
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 3âš¡
    server: data2hn3.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt2shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 4âš¡
    server: data2hn4.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: dt2shopvpn4g
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 5âš¡
    server: data2hcm1.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt1shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 6âš¡
    server: data2hcm2.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: data1shopvpn4g
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 7âš¡
    server: data2hcm3.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt1shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 8âš¡
    server: data2hcm4.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: data1shopvpn4g
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 1âš¡
    server: data1hn1.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt1shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 2âš¡
    server: data1hn2.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: dt1shopvpn4g
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 3âš¡
    server: data1hn3.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt1shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 4âš¡
    server: data1hn4.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: dt1shopvpn4g
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 5âš¡
    server: data1hn5.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt1shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 6âš¡
    server: data1hn6.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: data1shopvpn4g
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 7âš¡
    server: data1hcm1.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: ws
    ws-opts:
      path: /dt1shopvpn4g
      headers:
        Host: dl.kgvn.garenanow.com
    udp: true
  - name: ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 8âš¡
    server: data1hcm2.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: dl.kgvn.garenanow.com
    network: grpc
    grpc-opts:
      grpc-service-name: data1shopvpn4g
    udp: true
  - name: Japan JP2
    server: japanvip2.shopvpn4g.vn
    port: 80
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: www.linemo.jp
    network: ws
    ws-opts:
      path: shopvpn4g.vn
      headers:
        Host: www.linemo.jp
    udp: true
  - name: Japan 4
    server: japanvip4.shopvpn4g.vn
    port: 443
    type: vmess
    uuid: acca86b8-fd00-4bba-9a06-a11dee74ef26
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: www.linemo.jp
    network: grpc
    grpc-opts:
      grpc-service-name: shopvpn4g.vn
    udp: true
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - Singapore 1
      - Singapore 2 - [TLS]
      - Singapore 3
      - Singapore 4 - [TLS]
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 1âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 2âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 3âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 4âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 5âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 7âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 8âš¡ğŸ‘‘
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 1âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 2âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 3âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 4âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 5âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 6âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 7âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 8âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 1âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 2âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 3âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 4âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 5âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 6âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 7âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 8âš¡
      - Japan JP2
      - Japan 4
      - LOAD-BALANCE
      - BEST-PING
      - FALLBACK
      - DIRECT
  - name: LOAD-BALANCE
    type: load-balance
    strategy: consistent-hashing
    url: http://hi.bonds.id/ping
    interval: 300
    proxies:
      - Singapore 1
      - Singapore 2 - [TLS]
      - Singapore 3
      - Singapore 4 - [TLS]
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 1âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 2âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 3âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 4âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 5âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 7âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 8âš¡ğŸ‘‘
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 1âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 2âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 3âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 4âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 5âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 6âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 7âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 8âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 1âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 2âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 3âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 4âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 5âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 6âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 7âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 8âš¡
      - Japan JP2
      - Japan 4
  - name: BEST-PING
    type: url-test
    url: http://hi.bonds.id/ping
    interval: 300
    tolerance: 50
    proxies:
      - Singapore 1
      - Singapore 2 - [TLS]
      - Singapore 3
      - Singapore 4 - [TLS]
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 1âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 2âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 3âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 4âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 5âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 7âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 8âš¡ğŸ‘‘
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 1âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 2âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 3âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 4âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 5âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 6âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 7âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 8âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 1âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 2âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 3âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 4âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 5âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 6âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 7âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 8âš¡
      - Japan JP2
      - Japan 4
  - name: FALLBACK
    type: fallback
    url: http://hi.bonds.id/ping
    interval: 300
    proxies:
      - Singapore 1
      - Singapore 2 - [TLS]
      - Singapore 3
      - Singapore 4 - [TLS]
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 1âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 2âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 3âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 4âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 5âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 7âš¡ğŸ‘‘
      - ğ•ğ¢á»‡ğ­ ğğšğ¦ ğ•ğˆğğ’ğ„ğ‘ğ•ğ„ğ‘ 8âš¡ğŸ‘‘
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 1âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 2âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 3âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 4âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 5âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 6âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 7âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 8âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 1âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 2âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 3âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 4âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 5âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 6âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 7âš¡
      - ğƒğ“ğŸ ğ•ğ¢á»‡ğ­ ğğšğ¦ 8âš¡
      - Japan JP2
      - Japan 4
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY